# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://transparency-certified.github.io/
title: TRAnsparency CErtified (TRACE)
email: your-email@domain.com
description: > # "Building trust in computational research by certifying the transparency of results."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/wholetale
  - title: github
    url: https://github.com/transparency-certified/
