# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://transparency-certified.github.io/
title: TRAnsparency CErtified (TRACE)
email: your-email@domain.com
description: > # "Building trust in computational research by certifying the transparency of results."
hero_image: /img/trace-bg.jpg

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
markdown_ext: "markdown,md"

collections:
  jobs:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: "jobs"
    values:
      layout: "job"


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: slack
    icon: slack
    url: https://join.slack.com/t/wholetale/shared_invite/enQtNDM1OTg2ODU5MzUxLWJmZTg2MDQyOGNlYzY0ODZmYmFiN2ExZTI0NmZlMzZiZDFiNjU3MTFiYTZhODQwMDNlNTBjZGZhZWY0ZjFkZTk
  - title: github
    icon: github
    url: https://github.com/transparency-certified/
  - title: twitter
    icon: twitter
    url: https://twitter.com/wholetale
  - title: email
    icon: envelope
    url: mailto:transparencycertified@gmail.com

# ----------------------- #
#   Custom stuff          #
# ----------------------- #

menu:
  - title: Home
    url: "/"
  - title: Jobs
    url: "/jobs/"
  - title: Specification
    url: "/trace-specification/docs/specifications.html"
  - title: Infrastructure
    url: "/trace-specification/"
  - title: About
    url: "#about"
  - title: Contact
    url: "#contact"

footer:
  - img: "/img/UoI_wordmark.png"
    alt: "University of Illinois wordmark"
  - img: "/img/Cornell_wordmark.svg"
    alt: "Cornell University wordmark"
  - img: "/img/UNC_wordmark.png"
    alt: "University of North Carolina wordmark"